

source(here("src", "R", "create_de431_db_tables.R"))
source(here("src", "R", "populate_mercury_data.R"))
source(here("src", "R", "populate_venus_data.R"))
source(here("src", "R", "populate_emb_data.R"))
source(here("src", "R", "populate_mars_data.R"))
source(here("src", "R", "populate_jupiter_data.R"))
source(here("src", "R", "populate_saturn_data.R"))
source(here("src", "R", "populate_uranus_data.R"))
source(here("src", "R", "populate_neptune_data.R"))
source(here("src", "R", "populate_pluto_data.R"))
source(here("src", "R", "populate_sun_data.R"))
source(here("src", "R", "populate_moon_data.R"))
source(here("src", "R", "populate_nutation_data.R"))
source(here("src", "R", "populate_database.R"))
source(here("src", "R", "position_body_ssb.R"))
source(here("src", "R", "position_moon_geo.R"))
source(here("src", "R", "position_earth_ssb.R"))
source(here("src", "R", "nutation_matrix.R"))
source(here("src", "R", "precession_matrix.R"))
source(here("src", "R", "time.R"))
source(here("src", "R", "date.R"))
source(here("src", "R", "math.R"))
source(here("src", "R", "apparent_place.R"))
