

source(here("src", "R", "create_de431_db_tables.R"))
source(here("src", "R", "populate_mercury_data.R"))
source(here("src", "R", "populate_venus_data.R"))
source(here("src", "R", "populate_emb_data.R"))
source(here("src", "R", "populate_mars_data.R"))
source(here("src", "R", "populate_jupiter_data.R"))
source(here("src", "R", "populate_saturn_data.R"))
source(here("src", "R", "populate_uranus_data.R"))
source(here("src", "R", "populate_neptune_data.R"))
source(here("src", "R", "populate_pluto_data.R"))
source(here("src", "R", "populate_sun_data.R"))
source(here("src", "R", "populate_moon_data.R"))
source(here("src", "R", "populate_nutation_data.R"))
source(here("src", "R", "populate_database.R"))
source(here("src", "R", "position_moon_geo.R"))
source(here("src", "R", "position_mercury_ssb.R"))
source(here("src", "R", "position_venus_ssb.R"))
source(here("src", "R", "position_emb_ssb.R"))
source(here("src", "R", "position_earth_ssb.R"))
source(here("src", "R", "position_mars_ssb.R"))
source(here("src", "R", "position_jupiter_ssb.R"))
source(here("src", "R", "position_saturn_ssb.R"))
source(here("src", "R", "position_uranus_ssb.R"))
source(here("src", "R", "position_neptune_ssb.R"))
source(here("src", "R", "position_pluto_ssb.R"))
source(here("src", "R", "position_sun_ssb.R"))
source(here("src", "R", "nutation_angles.R"))
source(here("src", "R", "obliquity.R"))
source(here("src", "R", "nutation_matrix.R"))
source(here("src", "R", "precession_matrix.R"))
source(here("src", "R", "constants.R"))
source(here("src", "R", "time.R"))
source(here("src", "R", "date.R"))
source(here("src", "R", "math.R"))
source(here("src", "R", "apparent_place_mercury.R"))
source(here("src", "R", "apparent_place_venus.R"))
source(here("src", "R", "apparent_place_mars.R"))
source(here("src", "R", "apparent_place_jupiter.R"))
source(here("src", "R", "apparent_place_saturn.R"))
source(here("src", "R", "apparent_place_uranus.R"))
source(here("src", "R", "apparent_place_neptune.R"))
source(here("src", "R", "apparent_place_pluto.R"))
source(here("src", "R", "apparent_place_moon.R"))
source(here("src", "R", "apparent_place_sun.R"))
source(here("src", "R", "observer_position_vector.R"))
source(here("src", "R", "sidereal_time.R"))



